"""Project structure detection and architecture.py scaffolding helpers."""

from __future__ import annotations

from pathlib import Path


_EXCLUDED_TOP_LEVEL_DIRS = {"tests", "test", "docs", "doc", "scripts", "build"}
_LAYER_GROUPS = [
    ("top", ["api", "views", "routes", "handlers", "endpoints"]),
    ("middle", ["services", "use_cases", "business"]),
    ("bottom", ["db", "database", "models", "repositories", "dal"]),
]


def _is_test_file(path: Path) -> bool:
    name = path.name
    lowered = name.lower()
    return lowered.startswith("test_") or lowered.endswith("_test.py")


def _iter_python_files(package_root: Path) -> list[Path]:
    files: list[Path] = []
    for path in package_root.rglob("*.py"):
        if "__pycache__" in path.parts:
            continue
        if any(part.lower() in {"tests", "test"} for part in path.parts):
            continue
        if _is_test_file(path):
            continue
        files.append(path)
    return files


def detect_project_structure(project_root: Path) -> dict[str, object]:
    """Detect package and architecture hints from a project root."""
    root = project_root.resolve()

    candidates: list[tuple[Path, int]] = []
    for child in root.iterdir():
        if not child.is_dir():
            continue
        if child.name in _EXCLUDED_TOP_LEVEL_DIRS:
            continue
        if not (child / "__init__.py").is_file():
            continue
        python_file_count = len(_iter_python_files(child))
        candidates.append((child, python_file_count))

    if not candidates:
        return {
            "top_level_package": None,
            "detected_layers": [],
            "has_internal": False,
            "internal_paths": [],
            "total_python_files": 0,
        }

    candidates.sort(key=lambda item: (-item[1], item[0].name))
    package_root, total_python_files = candidates[0]
    package_name = package_root.name

    detected_layers: list[str] = []
    for _, layer_names in _LAYER_GROUPS:
        for layer_name in layer_names:
            layer_path = package_root / layer_name
            if layer_path.is_dir():
                detected_layers.append(f"{package_name}.{layer_name}")

    internal_paths: list[str] = []
    for directory in package_root.rglob("internal"):
        if not directory.is_dir():
            continue
        if "__pycache__" in directory.parts:
            continue
        relative = directory.relative_to(package_root)
        module_path = ".".join([package_name, *relative.parts])
        internal_paths.append(module_path)

    internal_paths = sorted(set(internal_paths))

    return {
        "top_level_package": package_name,
        "detected_layers": detected_layers,
        "has_internal": bool(internal_paths),
        "internal_paths": internal_paths,
        "total_python_files": total_python_files,
    }


def generate_architecture_py(structure: dict[str, object]) -> str:
    """Generate architecture.py content from detected structure metadata."""
    top_level_package = structure.get("top_level_package")
    detected_layers = list(structure.get("detected_layers", []))
    internal_paths = list(structure.get("internal_paths", []))

    needs_layers_rule = len(detected_layers) >= 2
    needs_boundaries = bool(internal_paths)
    needs_placeholder = not detected_layers

    base_imports = ["rule"]
    if needs_placeholder:
        base_imports.append("imports")

    rule_imports = ["no_cycles"]
    if needs_layers_rule:
        rule_imports.append("layers")
    if needs_boundaries:
        rule_imports.append("module")

    lines: list[str] = [
        "# Generated by `archetype init`; customize these rules for your architecture.",
        "",
        f"from archetype import {', '.join(base_imports)}",
        f"from archetype.rules import {', '.join(rule_imports)}",
        "",
    ]

    if needs_layers_rule:
        lines.extend(
            [
                "# Enforces that lower-level layers do not import higher-level layers.",
                "@rule('enforce-layer-order')",
                "def _enforce_layer_order() -> None:",
                f"    layers({detected_layers!r}).are_ordered()",
                "",
            ]
        )

    for internal_path in internal_paths:
        parent = internal_path.rsplit(".internal", 1)[0]
        lines.extend(
            [
                f"# Enforces that {internal_path} is imported only from within {parent}.",
                f"@rule('protect-{internal_path.replace('.', '-')}')",
                f"def _protect_{internal_path.replace('.', '_')}() -> None:",
                f"    module('{internal_path}').only_imported_within('{parent}')",
                "",
            ]
        )

    if needs_placeholder:
        source_package = (
            top_level_package if isinstance(top_level_package, str) else "your_package"
        )
        lines.extend(
            [
                "# Demonstrates a forbidden dependency rule you should customize for this project.",
                "@rule('placeholder-forbidden-import')",
                "def _placeholder_forbidden_import() -> None:",
                f"    imports('{source_package}').must_not_import('{source_package}.infrastructure')",
                "",
            ]
        )

    cycle_target = top_level_package if isinstance(top_level_package, str) else None
    lines.extend(
        [
            "# Enforces that import cycles are not allowed in the selected module scope.",
            "@rule('no-import-cycles')",
            "def _no_import_cycles() -> None:",
            (
                f"    no_cycles('{cycle_target}')"
                if cycle_target is not None
                else "    no_cycles()"
            ),
            "",
        ]
    )

    return "\n".join(lines)


def find_existing_architecture_py(project_root: Path) -> Path | None:
    """Return the existing architecture.py path in project root if present."""
    architecture_path = project_root.resolve() / "architecture.py"
    return architecture_path if architecture_path.is_file() else None


def write_architecture_py(project_root: Path, content: str) -> Path:
    """Write architecture.py in project root without overwriting existing files."""
    architecture_path = project_root.resolve() / "architecture.py"
    if architecture_path.exists():
        raise FileExistsError(f"architecture.py already exists at {architecture_path}")
    architecture_path.write_text(content, encoding="utf-8")
    return architecture_path
